name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          root_file: seminararbeit.tex
      - run: mkdir -p doc
      - run: cp seminararbeit.pdf doc/seminararbeit.pdf
      - name: Provide PDF
        uses: actions/upload-artifact@master
        with:
          name: seminararbeit
          path: doc